#Theoretical question

Q1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans NumPy, short for "Numerical Python," is a fundamental package for scientific computing and data analysis in Python. It provides a powerful n-dimensional array object, tools for integrating C/C++ and Fortran code, and useful linear algebra, Fourier transform, and random number capabilities. Here’s a look at its purpose and advantages:

1. Efficient Array and Matrix Operations
NumPy introduces the ndarray (N-dimensional array) object, which is a fast, flexible container for large data sets, allowing operations over entire arrays rather than requiring element-by-element operations. This capability enhances Python's handling of matrices and arrays, making it easy to perform complex mathematical operations across entire data structures efficiently.

2. Performance Optimization
Python’s default lists are not well-suited for numerical computation due to their lack of support for vectorized operations and their slow processing speeds. NumPy arrays, by contrast, are:

Memory-efficient: Arrays consume less memory than Python lists due to the way NumPy stores elements in contiguous memory.
Highly optimized for speed: NumPy is implemented in C, allowing faster computation by reducing the need for explicit loops and taking advantage of low-level optimizations.
3. Vectorized Operations and Broadcasting
NumPy’s vectorized operations allow mathematical and logical operations to be performed on entire arrays without explicit loops. Broadcasting further allows these operations to happen even between arrays of different shapes, avoiding the need to reshape or duplicate data unnecessarily. This makes it ideal for large-scale data manipulation, especially in data science and machine learning workflows where operations over matrices and vectors are common.

4. Comprehensive Mathematical Functions
NumPy provides a suite of mathematical functions that cover a wide array of domains, including linear algebra, statistical analysis, and complex math. This extensive library of functions makes it easy to perform many mathematical operations efficiently without needing to reinvent functions or install multiple libraries.

5. Interoperability with Other Libraries
NumPy serves as the backbone for other major data analysis libraries in Python, like Pandas, SciPy, Scikit-Learn, and TensorFlow. It provides a standard for data arrays that other libraries can work with directly, making it easy to move data between libraries without conversion, enhancing overall productivity in scientific workflows.

6. Integration with C/C++ and Fortran
NumPy makes it easier to integrate C/C++ and Fortran code into Python, making it possible to leverage legacy code or highly optimized algorithms written in these languages. This capability is crucial for high-performance computing tasks, as it allows for both ease of use with Python and the speed of compiled languages.

7. Community and Documentation
NumPy has a vast user community and extensive documentation. As a widely used library, it offers numerous tutorials, forums, and examples that facilitate learning and troubleshooting, which is particularly beneficial for researchers and data scientists.

In Summary
NumPy extends Python’s capabilities in scientific computing and data analysis by providing optimized, fast, and memory-efficient data structures for handling numerical data. Its array operations, performance benefits, comprehensive functions, and interoperability make it an essential tool for anyone working in data science, machine learning, or engineering computations.

Q2  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans In NumPy, both np.mean() and np.average() functions compute the average of array elements, but they have some key differences in functionality and use cases.
1. np.mean()
Purpose: Computes the arithmetic mean (average) of array elements along a specified axis or for the flattened array by default.
Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=<no value>)
Key Points:
Does not accept weights, so each element is treated equally.
Often faster and more lightweight due to the absence of weight processing.
Example:

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
mean = np.mean(arr)
print(mean)  # Output: 2.5


2.5


2. np.average()
Purpose: Computes the weighted average of array elements if weights are provided; otherwise, it behaves similarly to np.mean().
Syntax: np.average(array, axis=None, weights=None, returned=False)
Key Points:
Weights: Can accept a weights parameter, which allows you to specify an array of weights that scales each element of the input array.
Return Sum of Weights: With returned=True, it returns a tuple of the average and the sum of weights.
Without weights, np.average() is essentially the same as np.mean().
Example:

In [2]:
import numpy as np # Importing the numpy library and aliasing it as 'np'

arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
weighted_avg = np.average(arr, weights=weights)
print(weighted_avg)  # Output: 3.0 (due to weighting)

3.0


When to Use Each
Use np.mean() when you need a straightforward arithmetic mean without any weighting, especially when performance is a priority.
Use np.average() when you need a weighted mean, as np.mean() does not support weighting. It's useful in situations where different elements have varying levels of importance.
In summary:

np.mean() is ideal for unweighted means and simplicity.
np.average() provides more flexibility with weighted means but has additional overhead if weights aren’t needed.







Q3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans Reversing a NumPy array along different axes can be achieved with various methods, including slicing, the np.flip function, and the np.flipud and np.fliplr functions. Below are detailed examples for reversing both 1D and 2D arrays.
1. Reversing a 1D Array
For a 1D array, reversing it is simple. You can use slicing or np.flip.
Example:  

In [4]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Method 1: Using slicing
reversed_arr_1d = arr_1d[::-1]

# Method 2: Using np.flip
reversed_arr_1d_flip = np.flip(arr_1d)

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array (slicing):", reversed_arr_1d)
print("Reversed 1D Array (np.flip):", reversed_arr_1d_flip)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array (slicing): [5 4 3 2 1]
Reversed 1D Array (np.flip): [5 4 3 2 1]


2. Reversing a 2D Array
In a 2D array, you can reverse along different axes (rows or columns) or both. Here are some methods:

Example:

In [ ]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Method 1: Reverse along rows (axis=0)
reversed_arr_2d_rows = arr_2d[::-1, :]

# Method 2: Reverse along columns (axis=1)
reversed_arr_2d_cols = arr_2d[:, ::-1]

# Method 3: Reverse both rows and columns
reversed_arr_2d_both = arr_2d[::-1, ::-1]

# Method 4: Using np.flip along axis 0 (rows)
reversed_arr_2d_flip_rows = np.flip(arr_2d, axis=0)

# Method 5: Using np.flip along axis 1 (columns)
reversed_arr_2d_flip_cols = np.flip(arr_2d, axis=1)

print("Original 2D Array:\n", arr_2d)
print("Reversed 2D Array along rows:\n", reversed_arr_2d_rows)
print("Reversed 2D Array along columns:\n", reversed_arr_2d_cols)
print("Reversed 2D Array along both rows and columns:\n", reversed_arr_2d_both)
print("Reversed 2D Array (np.flip, axis=0):\n", reversed_arr_2d_flip_rows)
print("Reversed 2D Array (np.flip, axis=1):\n", reversed_arr_2d_flip_cols)


Explanation of Each Method
Slicing: This uses negative indexing to reverse the array along specified dimensions.
np.flip: Allows for specifying the axis to reverse. In 2D, axis=0 reverses rows, and axis=1 reverses columns.
np.flipud and np.fliplr: np.flipud reverses along rows, while np.fliplr reverses along columns for 2D arrays.

Q4  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans To determine the data type of elements in a NumPy array, you can use the dtype attribute. Here’s an example:

In [5]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3])

# Get the data type of the array elements
print(arr.dtype)


int64


In this example, arr.dtype will output the data type of the elements in the array, such as int32, float64, etc., depending on the values and specified type.

Importance of Data Types in Memory Management and Performance
Memory Management:

Each data type in NumPy corresponds to a specific amount of memory. For instance, an int32 (32-bit integer) requires 4 bytes per element, while an int64 (64-bit integer) requires 8 bytes per element.
Choosing the correct data type based on your data’s requirements can significantly reduce memory usage. For example, if you only need to store integers within a small range, using int8 or int16 rather than int64 can save considerable memory, especially with large datasets.
Performance:

NumPy arrays are often used in large-scale numerical computations. Smaller data types allow for faster data access and processing, as the system can load more data into memory at once.
Operations on arrays with smaller data types (e.g., int32 vs. int64) can be faster since they require fewer CPU cycles and take up less space in the CPU cache, which improves computation speed.
By selecting an appropriate data type, you can optimize both memory usage and performance, which is crucial in high-performance computing, machine learning, and data science applications where efficiency matters.

Q5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans In NumPy, an ndarray (n-dimensional array) is the core data structure, representing a grid of values, all of which are of the same data type. Unlike standard Python lists, which can hold heterogeneous data types (e.g., integers, floats, strings) and vary in length, ndarrays are designed for efficient numerical computations and are optimized for operations on large datasets.

Key Features of ndarrays
Homogeneous Data: All elements in an ndarray have the same data type, making it more memory-efficient than lists.
Fixed Size: Once created, the size of an ndarray is fixed. You cannot add or remove elements directly, though you can create a new array with modifications.
N-dimensional Structure: ndarrays can have multiple dimensions (1D, 2D, 3D, etc.), allowing for representation of more complex data like matrices and tensors.
Efficient Memory Layout: The data is stored in contiguous memory blocks, which enhances performance, especially for large arrays, as it allows NumPy to leverage low-level optimizations.
Broadcasting: This feature enables operations between arrays of different shapes, such as adding a scalar to a matrix or two arrays of different sizes in a way that expands the smaller array to match the larger one.
Vectorized Operations: ndarrays allow for element-wise operations without explicit loops, using highly optimized C and Fortran code under the hood.
Numerical Functions: NumPy provides a rich library of mathematical functions, statistical tools, and linear algebra routines specifically designed to work with ndarrays.
Differences from Standard Python Lists
Type Consistency: Python lists can hold elements of mixed data types, whereas ndarrays enforce a single data type for all elements.
Speed and Memory Efficiency: ndarrays are more memory- and speed-efficient due to contiguous memory storage, which avoids the need for Python's overhead of handling different types.
Operations and Broadcasting: Lists do not support broadcasting, vectorized operations, or many of the advanced mathematical functions available in NumPy for ndarrays.
Dimensional Flexibility: While lists can represent n-dimensional data through nested lists, ndarrays handle n-dimensional data natively, providing more flexibility and easier manipulation for multi-dimensional data.
Example
Here's a simple comparison between a Python list and an ndarray:

In [ ]:
# Standard Python list
lst = [1, 2, 3, 4]
# NumPy ndarray
import numpy as np
arr = np.array([1, 2, 3, 4])


Now, multiplying each element by 2 would work differently:

In [ ]:
# Multiplying elements in the list
lst_multiplied = [x * 2 for x in lst]  # Output: [2, 4, 6, 8]

# Multiplying elements in the ndarray
arr_multiplied = arr * 2  # Output: array([2, 4, 6, 8])


In the case of ndarrays, the operation is vectorized, providing a cleaner syntax and greater efficiency.

Q6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

Ans NumPy arrays offer several performance advantages over Python lists when dealing with large-scale numerical operations, largely due to their specialized data structures and optimization for numerical computation. Here’s an analysis of the key benefits:

1. Memory Efficiency
Fixed Data Type: NumPy arrays are homogeneously typed, meaning all elements in a NumPy array must be of the same type, typically float32, float64, or int32, among others. This allows them to use a contiguous block of memory for each array, whereas Python lists store pointers to Python objects, which introduces overhead.
Smaller Memory Footprint: Since a NumPy array stores only the raw data without the extra object metadata that Python lists need, it can fit more data in memory and reduces memory consumption, especially for large datasets.
2. Improved Performance
Vectorized Operations: NumPy supports vectorized operations, which allow arithmetic operations to be applied on entire arrays or slices without the need for explicit loops. For instance, adding two arrays in NumPy can be done with array1 + array2 rather than looping through each element, reducing Python interpreter overhead and significantly speeding up execution.
Lower-Level Implementations: NumPy is implemented in C and optimized for performance at a low level, with efficient use of CPU cache and avoidance of the Python interpreter's overhead. This low-level optimization enables faster execution, particularly for operations that would otherwise require a loop in Python.
3. SIMD and Multithreading
SIMD (Single Instruction, Multiple Data): NumPy operations are often vectorized with SIMD instructions, allowing the CPU to process multiple elements of the array in a single instruction cycle. This can greatly enhance performance for mathematical and logical operations over large arrays.
Multithreaded Processing: Some NumPy functions are implemented to leverage multiple CPU cores where available, which speeds up operations further. For example, linear algebra operations and some mathematical functions can distribute computations across cores.
4. Optimized Built-in Functions
Broad Library of Fast Functions: NumPy offers a wide range of highly optimized functions for mathematical operations, including matrix manipulation, statistical analysis, and more. These built-in functions are usually much faster than custom implementations in pure Python.
Memory Management: NumPy minimizes memory allocation by reusing memory locations whenever possible. Operations that would create new objects in Python, like slicing and reshaping, are designed to share data with the original array without making copies, leading to faster operations and reduced memory usage.
5. Batch Processing
Reduced Overhead for Large-Scale Data: NumPy’s batch processing capability allows operations to be applied to all elements of a large array at once. With Python lists, batch operations would require additional looping or list comprehensions, which introduces significant overhead for large datasets.
Performance Summary
In benchmarks, NumPy arrays can outperform Python lists by orders of magnitude, especially for large data volumes and computationally intensive tasks. For example, element-wise arithmetic operations on large datasets can be 10x to 100x faster in NumPy than Python lists due to memory efficiency, vectorization, and reduced overhead from interpreter calls.

Conclusion
For large-scale numerical and scientific computations, NumPy arrays offer major performance benefits over Python lists, making them the go-to choice for data manipulation, especially in fields like data science, machine learning, and scientific computing.

Q7  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

vstack(): This function is used to stack arrays vertically, meaning row-wise. It combines two or more arrays along the vertical axis (axis=0).

Syntax: numpy.vstack((array1, array2, ...))
Requirements: The arrays being stacked must have the same number of columns.
hstack(): This function stacks arrays horizontally, meaning column-wise. It combines two or more arrays along the horizontal axis (axis=1).

Syntax: numpy.hstack((array1, array2, ...))
Requirements: The arrays must have the same number of rows.
Examples
Let's look at examples of both functions to see how they work.

In [ ]:
import numpy as np

# Define two arrays with the same number of columns
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Using vstack to stack arrays vertically
vstack_result = np.vstack((array1, array2))
print("vstack result:\n", vstack_result)

# Define two arrays with the same number of rows
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])

# Using hstack to stack arrays horizontally
hstack_result = np.hstack((array3, array4))
print("\nhstack result:\n", hstack_result)


Output

In [8]:
vstack result:
 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

hstack result:
 [[1 2 5 6]
  [3 4 7 8]]


SyntaxError: invalid syntax (<ipython-input-8-753323246f03>, line 1)

Explanation
vstack() stacked array1 and array2 vertically, creating a 4x3 array by adding array2 as new rows beneath array1.
hstack() stacked array3 and array4 horizontally, creating a 2x4 array by adding array4 as new columns to the right of array3.

Q8  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans In NumPy, fliplr() and flipud() are functions used to reverse the order of elements in arrays, but they operate along different dimensions:

1. fliplr()
Meaning: "Flip Left to Right"
Effect: It reverses the order of columns in a 2D array, effectively flipping the array along the vertical axis.
Usage: np.fliplr(array)
Supported Dimensions: Primarily for 2D arrays, though it can also operate on the last two dimensions of higher-dimensional arrays.
Example:
For a 2D array:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.fliplr(arr)
print(flipped_arr)


Output:

In [ ]:
[[3, 2, 1],
 [6, 5, 4]]


2. flipud()
Meaning: "Flip Up to Down"
Effect: It reverses the order of rows in a 2D array, effectively flipping the array along the horizontal axis.
Usage: np.flipud(array)
Supported Dimensions: Like fliplr, it is designed for 2D arrays but can work on the first two dimensions of higher-dimensional arrays.
Example:
For the same 2D array

In [ ]:
flipped_arr_ud = np.flipud(arr)
print(flipped_arr_ud)


Output:

In [ ]:
[[4, 5, 6],
 [1, 2, 3]]


Summary
fliplr() flips the array horizontally (left to right).
flipud() flips the array vertically (up to down).
In 3D or higher-dimensional arrays, fliplr() flips along the last axis and flipud() along the first axis, but both affect only the two axes they are designed for. For more complex flipping, consider np.flip(), which allows custom axis selection.

Q9  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans
The array_split() function in NumPy is used to split an array into multiple sub-arrays. This function is particularly useful when dividing an array into a specified number of chunks, even if the array length doesn't divide evenly into those chunks.

Function Syntax

In [ ]:
numpy.array_split(array, sections, axis=0)


array: The input array to be split.
sections: The number of equal (or as close as possible) sections to divide the array into, or a list of indices specifying where to split.
axis: The axis along which to split the array (default is axis=0, or row-wise).
Handling Uneven Splits
When the array's length cannot be split evenly into the specified number of sections, array_split() distributes the remainder across the earlier sections. This ensures that all output arrays have nearly equal lengths, with the first few being slightly longer if necessary.

Example:

In [ ]:
import numpy as np

# Original array
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Splitting into 3 parts
split_arrays = np.array_split(array, 3)

print(split_arrays)


Output:

In [10]:
import numpy as np

# Original array
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Splitting into 3 parts
split_arrays = np.array_split(array, 3)

# Print the split arrays.
# Using 'print(split_arrays)' will automatically display the sub-arrays
# without needing to specify 'array()'.
print(split_arrays)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In this example:

The original array has 7 elements, which cannot be divided equally into 3 parts.
array_split() returns 3 arrays, where the first has 3 elements and the others have 2 each.
Key Points
array_split() is a flexible way to handle uneven splits, ensuring that the array splits are as even as possible.
Unlike split(), which throws an error if the array cannot be divided evenly, array_split() adjusts the size of the sub-arrays accordingly.
This flexibility makes array_split() especially useful in applications where the exact array length is unknown or dynamic.

Q10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans Vectorization and broadcasting are two fundamental techniques in NumPy that greatly enhance the efficiency of array operations. Let's break down each concept and understand how they contribute to performance improvements.

Vectorization
Vectorization is the process of rewriting operations so they can be applied directly to entire arrays (or "vectors") rather than processing elements one by one in loops. In NumPy, vectorized operations leverage highly optimized, low-level implementations (often in C) that allow operations to execute much faster than equivalent Python loops.

For example:

In [12]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
c = a + b  # No loop needed


In this code, adding a and b is a vectorized operation. NumPy performs the addition for each corresponding element in a single step, avoiding the need for an explicit for loop in Python. This approach is faster and more concise.

Benefits of Vectorization:

Speed: By avoiding Python loops and utilizing fast C-based implementations, vectorized operations are significantly faster.
Code Simplicity: Vectorized code is typically cleaner and more concise.
Reduced Overhead: Less interpreter overhead is needed since fewer Python operations are performed.
Broadcasting
Broadcasting allows NumPy to handle operations on arrays of different shapes in a way that is both memory-efficient and fast. When two arrays with different shapes are used in an operation, NumPy "stretches" the smaller array across the larger one to make their shapes compatible. However, rather than actually copying data, NumPy "broadcasts" the smaller array in a way that it appears as if it were the same shape as the larger array.

For example:

python
Copy code
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[1], [2], [3]])  # Shape (3, 1)

# Broadcasting allows element-wise addition, treating 'a' as if it were shape (3, 3)
result = a + b
Here, a with shape (3,) is broadcast to (3, 3) to match b, enabling the element-wise addition.

Rules for Broadcasting:

If the two arrays have different numbers of dimensions, prepend 1s to the shape of the smaller array until the dimensions match.
Arrays with a dimension of size 1 can be "stretched" to match the other array's dimension size.
If any dimension sizes do not match (and neither is 1), broadcasting fails, and an error is raised.
Benefits of Broadcasting:

Memory Efficiency: Broadcasting avoids the need to create large intermediate arrays, saving memory and speeding up computation.
Performance: By avoiding unnecessary data duplication, broadcasting allows operations to run faster and makes code more concise.
How They Contribute to Efficient Array Operations
Together, vectorization and broadcasting enable:

Reduced Computational Complexity: Operations are executed at a lower level and on multiple elements simultaneously.
Memory Efficiency: Broadcasting reduces memory requirements by avoiding extra array creation.
Improved Readability: Cleaner, more concise code as explicit loops and temporary variables are minimized.
This combination allows NumPy to perform operations quickly and with minimal memory use, making it ideal for handling large datasets and complex numerical computations.

#Practical question

Q1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

Ans Here’s the original 3x3 NumPy array with random integers between 1 and 100:

In [13]:
[[51, 77, 59],
 [34, 91, 68],
 [ 5, 38, 44]]


[[51, 77, 59], [34, 91, 68], [5, 38, 44]]

After interchanging its rows and columns (transposing the array), we get:

In [ ]:
[[51, 34,  5],
 [77, 91, 38],
 [59, 68, 44]]


In [14]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_array = array_3x3.T

array_3x3, transposed_array


(array([[37, 63, 77],
        [68,  9, 26],
        [41, 76, 92]]),
 array([[37, 68, 41],
        [63,  9, 76],
        [77, 26, 92]]))

Q2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

Ans Here are the results of your request:

1D NumPy Array:

array
=
[
0
,
1
,
2
,
3
,
4
,
5
,
6
,
7
,
8
,
9
]
array=[0,1,2,3,4,5,6,7,8,9]
Reshaped into a 2x5 Array:

array
2
×
5
=
[
0
1
2
3
4
5
6
7
8
9
]
array
2×5
​
 =[
0
5
​
  
1
6
​
  
2
7
​
  
3
8
​
  
4
9
​
 ]
Reshaped into a 5x2 Array:

\text{array}_{5 \times 2} = \begin{bmatrix} 0 & 1 \\ 2 & 3 \\ 4 & 5 \\ 6 & 7 \\ 8 & 9 \end{bmatrix} \] &#8203;:contentReference[oaicite:0]{index=0}&#8203;

Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans
Here’s a 6x6 NumPy array with a border of zeros around a 4x4 array of random float values:

[
0
0
0
0
0
0
0
0.3441
0.5244
0.1210
0.5352
0
0
0.1055
0.2753
0.9675
0.6847
0
0
0.8855
0.1506
0.8943
0.7714
0
0
0.3230
0.6506
0.4736
0.8288
0
0
0
0
0
0
0
]
​
  
0
0
0
0
0
0
​
  
0
0.3441
0.1055
0.8855
0.3230
0
​
  
0
0.5244
0.2753
0.1506
0.6506
0
​
  
0
0.1210
0.9675
0.8943
0.4736
0
​
  
0
0.5352
0.6847
0.7714
0.8288
0
​
  
0
0
0
0
0
0
​
  
​

The inner 4x4 array contains random values, while the outer border is filled with zeros. ​

In [15]:
import numpy as np

# Create a 4x4 array with random float values
random_array = np.random.rand(4, 4)

# Add a border of zeros around the array
bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

bordered_array


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.9458699 , 0.5714799 , 0.93457403, 0.41934545,
        0.        ],
       [0.        , 0.32890265, 0.34161884, 0.3937265 , 0.93993715,
        0.        ],
       [0.        , 0.55392515, 0.57367109, 0.36088047, 0.65729421,
        0.        ],
       [0.        , 0.06788886, 0.15742688, 0.83002647, 0.08583036,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [16]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
array


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Q5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [17]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(arr)        # Uppercase
lower_case = np.char.lower(arr)        # Lowercase
title_case = np.char.title(arr)        # Title case
capitalize_case = np.char.capitalize(arr)  # Capitalize first letter

# Combine the results into a structured array for better visualization
transformed_array = np.array(list(zip(upper_case, lower_case, title_case, capitalize_case)),
                             dtype=[('Upper', 'U10'), ('Lower', 'U10'), ('Title', 'U10'), ('Capitalize', 'U10')])

transformed_array


array([('PYTHON', 'python', 'Python', 'Python'),
       ('NUMPY', 'numpy', 'Numpy', 'Numpy'),
       ('PANDAS', 'pandas', 'Pandas', 'Pandas')],
      dtype=[('Upper', '<U10'), ('Lower', '<U10'), ('Title', '<U10'), ('Capitalize', '<U10')])

Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

Ans You can create a NumPy array of words and then insert a space between each character of every word using the following code:

In [ ]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print(spaced_words)


This code creates a NumPy array called words, then uses a list comprehension to join each character in the words with a space and stores the result in a new NumPy array called spaced_words.

When you run this code, the output will be:

In [18]:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


['h e l l ow o r l dn u m p ya r r a y']

Q7  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [21]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

addition, subtraction, multiplication, division


(array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]]),
 array([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]]),
 array([[0.11111111, 0.25      , 0.42857143],
        [0.66666667, 1.        , 1.5       ],
        [2.33333333, 4.        , 9.        ]]))

In [20]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

addition, subtraction, multiplication, division


(array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]]),
 array([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]]),
 array([[0.11111111, 0.25      , 0.42857143],
        [0.66666667, 1.        , 1.5       ],
        [2.33333333, 4.        , 9.        ]]))

Q8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

identity_matrix, diagonal_elements


In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

identity_matrix, diagonal_elements


Q9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
import numpy as np
from sympy import isprime

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if isprime(num)]

random_integers, prime_numbers


In [ ]:
import numpy as np
from sympy import isprime

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if isprime(num)]

random_integers, prime_numbers


Q10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [ ]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
# Assuming temperatures are in degrees Celsius
np.random.seed(42)  # For reproducibility
daily_temperatures = np.random.randint(low=15, high=30, size=30)

# Calculate weekly averages (4 weeks)
weekly_averages = np.mean(daily_temperatures.reshape(-1, 7), axis=1)

daily_temperatures, weekly_averages


In [ ]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
# Assuming temperatures are in degrees Celsius
np.random.seed(42)  # For reproducibility
daily_temperatures = np.random.randint(low=15, high=30, size=30)

# Calculate weekly averages (4 weeks)
weekly_averages = np.mean(daily_temperatures.reshape(-1, 7), axis=1)

daily_temperatures, weekly_averages
